services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123321awd
      MYSQL_DATABASE: tododb
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123321awd
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
      interval: 10s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 123321awd
    ports:
      - "8080:80"
  
  aspnetapp:
    build:
      context: .
      dockerfile: ToDoList/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ConnectionStrings:Database=Server=db;Port=3306;Database=tododb;User=admin;Password=123321awd;
      - ASPNETCORE_HTTP_PORTS=8081;